-- Citation Radar local database schema.
-- Stored in: <Zotero data dir>/citation-radar.sqlite (separate from Zotero's main DB).
-- Apply via storage/db.ts on first run; future migrations under storage/migrations/.

CREATE TABLE IF NOT EXISTS schema_version (
  version     INTEGER PRIMARY KEY,
  applied_at  INTEGER NOT NULL
);

-- Each row = a paper we've ever seen (may or may not be in user's Zotero library).
CREATE TABLE IF NOT EXISTS paper (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  zotero_item_id  INTEGER UNIQUE,            -- nullable: external papers also stored
  doi             TEXT,
  openalex_id     TEXT,
  s2_id           TEXT,
  title           TEXT NOT NULL,
  year            INTEGER,
  authors_json    TEXT,                      -- JSON array of {name, orcid?}
  venue           TEXT,
  abstract        TEXT,
  cited_by_count  INTEGER,
  fetched_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_paper_doi          ON paper(doi);
CREATE INDEX IF NOT EXISTS idx_paper_openalex     ON paper(openalex_id);
CREATE INDEX IF NOT EXISTS idx_paper_s2           ON paper(s2_id);
CREATE INDEX IF NOT EXISTS idx_paper_zotero_item  ON paper(zotero_item_id);

-- Citation edges: from_paper cites to_paper.
-- Multiple sources may report the same edge — store one row per (edge, source).
CREATE TABLE IF NOT EXISTS citation_edge (
  from_paper_id    INTEGER NOT NULL,
  to_paper_id      INTEGER NOT NULL,
  source           TEXT NOT NULL,            -- 'openalex' | 's2' | 'crossref'
  is_influential   INTEGER DEFAULT 0,        -- 1 if S2 marks influential
  context_snippet  TEXT,                     -- if source provides citation context
  PRIMARY KEY (from_paper_id, to_paper_id, source),
  FOREIGN KEY (from_paper_id) REFERENCES paper(id) ON DELETE CASCADE,
  FOREIGN KEY (to_paper_id)   REFERENCES paper(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_edge_from  ON citation_edge(from_paper_id);
CREATE INDEX IF NOT EXISTS idx_edge_to    ON citation_edge(to_paper_id);

-- Module A: influence reports generated by LLM.
CREATE TABLE IF NOT EXISTS influence_report (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  paper_id        INTEGER NOT NULL,
  generated_at    INTEGER NOT NULL,
  llm_model       TEXT,
  position_label  TEXT,                      -- 'seminal' | 'mainstream' | 'follow-up' | 'fringe' | 'review'
  summary_md      TEXT,                      -- human-readable Chinese report
  raw_json        TEXT,                      -- structured LLM output
  FOREIGN KEY (paper_id) REFERENCES paper(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_report_paper ON influence_report(paper_id);

-- Module B: faithfulness checks.
CREATE TABLE IF NOT EXISTS faithfulness_check (
  id                      INTEGER PRIMARY KEY AUTOINCREMENT,
  citing_paper_id         INTEGER NOT NULL,
  cited_paper_id          INTEGER,           -- nullable: cited paper may not be in library yet
  claim_text              TEXT NOT NULL,
  claim_location_json     TEXT,              -- {page, x, y, w, h, attachmentItemId}
  evidence_text           TEXT,
  evidence_location_json  TEXT,
  verdict                 TEXT NOT NULL,     -- 'supports' | 'partial' | 'contradicts' | 'unrelated' | 'unverifiable'
  llm_reasoning           TEXT,
  llm_model               TEXT,
  generated_at            INTEGER NOT NULL,
  FOREIGN KEY (citing_paper_id) REFERENCES paper(id) ON DELETE CASCADE,
  FOREIGN KEY (cited_paper_id)  REFERENCES paper(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_check_citing ON faithfulness_check(citing_paper_id);
CREATE INDEX IF NOT EXISTS idx_check_cited  ON faithfulness_check(cited_paper_id);

-- Generic API response cache (OpenAlex / S2 / Crossref).
CREATE TABLE IF NOT EXISTS api_cache (
  cache_key    TEXT PRIMARY KEY,
  payload      TEXT NOT NULL,
  fetched_at   INTEGER NOT NULL,
  ttl_seconds  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cache_fetched_at ON api_cache(fetched_at);
