// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-fetch-openalex'
  | 'pref-citedby-max'
  | 'pref-citedby-max-help'
  | 'pref-help'
  | 'pref-llm-key'
  | 'pref-llm-model'
  | 'pref-llm-provider'
  | 'pref-openalex-key'
  | 'pref-openalex-key-help'
  | 'pref-s2-key'
  | 'pref-s2-key-help'
  | 'pref-section-api-title'
  | 'pref-section-llm-title'
  | 'prefs-title'
  | 'startup-finish';
