// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "openAlexApiKey": string;
      "semanticScholarApiKey": string;
      "llmProvider": string;
      "llmModel": string;
      "llmApiKey": string;
    };
  }
}
